// Postgres schema for Aurral. Each migration runs once inside a transaction
// and is recorded in schema_migrations. Append new migrations; never edit an
// applied one.

const INITIAL_TABLES = `
  CREATE EXTENSION IF NOT EXISTS pg_trgm;

  -- NULL instead of an error for text that is not valid JSON, so index and
  -- trigger expressions tolerate legacy rows.
  CREATE OR REPLACE FUNCTION aurral_json(input TEXT) RETURNS JSONB
  LANGUAGE plpgsql IMMUTABLE STRICT AS $$
  BEGIN
    RETURN input::jsonb;
  EXCEPTION WHEN others THEN
    RETURN NULL;
  END;
  $$;

  CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS discovery_cache (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    last_updated TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS images_cache (
    mbid TEXT PRIMARY KEY,
    image_url TEXT,
    images_json TEXT,
    cache_age BIGINT,
    created_at TEXT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_images_cache_cache_age ON images_cache (cache_age);

  CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    permissions TEXT,
    discover_layout TEXT,
    lastfm_username TEXT,
    listen_history_provider TEXT,
    listen_history_username TEXT,
    listen_history_url TEXT,
    lidarr_root_folder_path TEXT,
    lidarr_quality_profile_id INTEGER
  );

  CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token TEXT UNIQUE NOT NULL,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    ip_address TEXT,
    user_agent TEXT
  );
  CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions (user_id);
  CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions (expires_at);

  CREATE TABLE IF NOT EXISTS lastfm_link_states (
    token_hash TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    browser_nonce_hash TEXT NOT NULL,
    expires_at BIGINT NOT NULL,
    consumed_at BIGINT,
    created_at BIGINT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_lastfm_link_states_expiry ON lastfm_link_states (expires_at);

  CREATE TABLE IF NOT EXISTS subsonic_stars (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    entity_kind TEXT NOT NULL,
    entity_key TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (user_id, entity_kind, entity_key)
  );
  CREATE INDEX IF NOT EXISTS idx_subsonic_stars_user_created ON subsonic_stars (user_id, created_at);

  CREATE TABLE IF NOT EXISTS play_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    track_id TEXT NOT NULL,
    title TEXT NOT NULL,
    artist TEXT NOT NULL,
    album TEXT,
    artist_mbid TEXT,
    album_mbid TEXT,
    track_mbid TEXT,
    duration_ms BIGINT,
    played_at BIGINT NOT NULL,
    source TEXT NOT NULL,
    created_at BIGINT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_play_events_user_played_at ON play_events (user_id, played_at DESC);

  CREATE TABLE IF NOT EXISTS playlist_download_jobs (
    id TEXT PRIMARY KEY,
    artist_name TEXT NOT NULL,
    track_name TEXT NOT NULL,
    album_name TEXT,
    reason TEXT,
    artist_mbid TEXT,
    album_mbid TEXT,
    track_mbid TEXT,
    release_year TEXT,
    duration_ms BIGINT,
    track_number INTEGER,
    album_track_count INTEGER,
    album_track_titles TEXT,
    artist_aliases TEXT,
    playlist_id TEXT NOT NULL,
    playlist_type TEXT,
    status TEXT NOT NULL,
    staging_path TEXT,
    final_path TEXT,
    external_path TEXT,
    error TEXT,
    started_at BIGINT,
    completed_at BIGINT,
    created_at BIGINT NOT NULL,
    download_source TEXT,
    download_client TEXT,
    download_client_id TEXT,
    release_guid TEXT,
    release_title TEXT,
    indexer_id TEXT,
    indexer_name TEXT,
    slskd_search_id TEXT,
    slskd_batch_id TEXT,
    remote_username TEXT,
    remote_filename TEXT,
    denied_remote_sources TEXT,
    quality_tier TEXT,
    quality_format TEXT,
    quality_bitrate_kbps INTEGER,
    quality_sample_rate_hz INTEGER,
    quality_bit_depth INTEGER,
    quality_checked_at BIGINT,
    quality_upgrade_checked_at BIGINT,
    upgrade_for_job_id TEXT
  );
  CREATE INDEX IF NOT EXISTS idx_playlist_download_jobs_status ON playlist_download_jobs (status);
  CREATE INDEX IF NOT EXISTS idx_playlist_download_jobs_playlist_id ON playlist_download_jobs (playlist_id);

  CREATE TABLE IF NOT EXISTS deezer_mbid_cache (
    cache_key TEXT PRIMARY KEY,
    mbid TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS musicbrainz_artist_mbid_cache (
    artist_name_key TEXT PRIMARY KEY,
    mbid TEXT,
    updated_at BIGINT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_musicbrainz_artist_mbid_cache_updated_at
    ON musicbrainz_artist_mbid_cache (updated_at);

  CREATE TABLE IF NOT EXISTS artist_overrides (
    mbid TEXT PRIMARY KEY,
    musicbrainz_id TEXT,
    deezer_artist_id TEXT,
    updated_at BIGINT
  );

  CREATE TABLE IF NOT EXISTS lidarr_artist_id_map (
    musicbrainz_id TEXT PRIMARY KEY,
    lidarr_foreign_artist_id TEXT NOT NULL UNIQUE,
    updated_at BIGINT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS library_artists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_key TEXT NOT NULL UNIQUE,
    mbid TEXT,
    name TEXT NOT NULL,
    sort_name TEXT,
    metadata_json TEXT,
    lidarr_fingerprint TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_library_artists_sort_name_name
    ON library_artists (lower(sort_name), lower(name));
  CREATE INDEX IF NOT EXISTS idx_library_artists_mbid ON library_artists (mbid);
  CREATE INDEX IF NOT EXISTS idx_library_artists_name ON library_artists (lower(name));
  CREATE INDEX IF NOT EXISTS idx_library_artists_provider_id
    ON library_artists ((aurral_json(metadata_json) ->> 'id'));
  CREATE INDEX IF NOT EXISTS idx_library_artists_foreign_artist_id
    ON library_artists ((aurral_json(metadata_json) ->> 'foreignArtistId'));

  CREATE TABLE IF NOT EXISTS library_albums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_key TEXT NOT NULL UNIQUE,
    mbid TEXT,
    release_group_mbid TEXT,
    artist_id BIGINT NOT NULL REFERENCES library_artists(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    album_artist TEXT,
    release_date TEXT,
    metadata_json TEXT,
    latest_media_at BIGINT NOT NULL DEFAULT 0,
    latest_available_media_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_library_albums_artist_id ON library_albums (artist_id);
  CREATE INDEX IF NOT EXISTS idx_library_albums_mbid ON library_albums (mbid);
  CREATE INDEX IF NOT EXISTS idx_library_albums_release_group_mbid ON library_albums (release_group_mbid);
  CREATE INDEX IF NOT EXISTS idx_library_albums_title ON library_albums (lower(title));
  CREATE INDEX IF NOT EXISTS idx_library_albums_release_date ON library_albums (release_date DESC);
  CREATE INDEX IF NOT EXISTS idx_library_albums_latest_media_at
    ON library_albums (latest_media_at DESC, lower(title));
  CREATE INDEX IF NOT EXISTS idx_library_albums_latest_available_media_at
    ON library_albums (latest_available_media_at DESC, lower(title));

  CREATE TABLE IF NOT EXISTS library_tracks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_key TEXT NOT NULL UNIQUE,
    mbid TEXT,
    title TEXT NOT NULL,
    artist_name TEXT,
    metadata_json TEXT,
    latest_media_at BIGINT NOT NULL DEFAULT 0,
    latest_available_media_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_library_tracks_title ON library_tracks (lower(title));
  CREATE INDEX IF NOT EXISTS idx_library_tracks_latest_media_at
    ON library_tracks (latest_media_at DESC, lower(title));
  CREATE INDEX IF NOT EXISTS idx_library_tracks_latest_available_media_at
    ON library_tracks (latest_available_media_at DESC, lower(title));

  CREATE TABLE IF NOT EXISTS library_album_tracks (
    album_id BIGINT NOT NULL REFERENCES library_albums(id) ON DELETE CASCADE,
    track_id BIGINT NOT NULL REFERENCES library_tracks(id) ON DELETE CASCADE,
    disc_number INTEGER NOT NULL DEFAULT 1,
    track_number INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (album_id, track_id, disc_number, track_number)
  );
  CREATE INDEX IF NOT EXISTS idx_library_album_tracks_track_id ON library_album_tracks (track_id);

  CREATE TABLE IF NOT EXISTS library_media_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id BIGINT NOT NULL REFERENCES library_tracks(id) ON DELETE CASCADE,
    album_id BIGINT,
    source TEXT NOT NULL,
    path TEXT NOT NULL,
    format TEXT,
    size BIGINT NOT NULL DEFAULT 0,
    mtime_ms BIGINT,
    duration_ms BIGINT,
    quality_json TEXT,
    available INTEGER NOT NULL DEFAULT 1,
    last_seen_scan_id BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE (source, path)
  );
  CREATE INDEX IF NOT EXISTS idx_library_media_files_track_id ON library_media_files (track_id);
  CREATE INDEX IF NOT EXISTS idx_library_media_files_track_source_available
    ON library_media_files (track_id, source, available);
  CREATE INDEX IF NOT EXISTS idx_library_media_files_source_available
    ON library_media_files (source, available);
  CREATE INDEX IF NOT EXISTS idx_library_media_files_scan_id ON library_media_files (last_seen_scan_id);
  CREATE INDEX IF NOT EXISTS idx_library_media_files_album_source_available
    ON library_media_files (album_id, source, available);
  CREATE INDEX IF NOT EXISTS idx_library_media_files_track_album_source_available
    ON library_media_files (track_id, album_id, source, available);

  CREATE TABLE IF NOT EXISTS library_scan_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    root_path TEXT,
    status TEXT NOT NULL,
    started_at BIGINT NOT NULL,
    completed_at BIGINT,
    error TEXT,
    files_seen INTEGER NOT NULL DEFAULT 0,
    files_indexed INTEGER NOT NULL DEFAULT 0,
    files_failed INTEGER NOT NULL DEFAULT 0
  );

  CREATE TABLE IF NOT EXISTS library_genres (
    entity_kind TEXT NOT NULL,
    entity_id BIGINT NOT NULL,
    genre TEXT NOT NULL,
    PRIMARY KEY (entity_kind, entity_id, genre)
  );
  CREATE INDEX IF NOT EXISTS idx_library_genres_genre
    ON library_genres (lower(genre), entity_kind, entity_id);

  CREATE TABLE IF NOT EXISTS library_search_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_kind TEXT NOT NULL,
    entity_id BIGINT NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    artist_name TEXT NOT NULL DEFAULT '',
    album_name TEXT NOT NULL DEFAULT '',
    search_text TEXT GENERATED ALWAYS AS (
      lower(title || ' ' || artist_name || ' ' || album_name)
    ) STORED,
    UNIQUE (entity_kind, entity_id)
  );
  CREATE INDEX IF NOT EXISTS idx_library_search_documents_trgm
    ON library_search_documents USING gin (search_text gin_trgm_ops);

  CREATE TABLE IF NOT EXISTS aurral_history (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    title TEXT NOT NULL,
    subtitle TEXT,
    status TEXT NOT NULL,
    status_label TEXT,
    href TEXT,
    metadata TEXT,
    created_at BIGINT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_aurral_history_created_at ON aurral_history (created_at DESC);

  CREATE TABLE IF NOT EXISTS inbox_items (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    source_key TEXT NOT NULL,
    title TEXT NOT NULL,
    subtitle TEXT,
    href TEXT,
    image_url TEXT,
    metadata TEXT,
    is_read INTEGER NOT NULL DEFAULT 0,
    is_saved INTEGER NOT NULL DEFAULT 0,
    is_dismissed INTEGER NOT NULL DEFAULT 0,
    is_added INTEGER NOT NULL DEFAULT 0,
    dismissed_until BIGINT,
    expires_at BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE (user_id, kind, source_key)
  );
  CREATE INDEX IF NOT EXISTS idx_inbox_items_user_state
    ON inbox_items (user_id, is_dismissed, is_read, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_inbox_items_expiry ON inbox_items (expires_at, created_at DESC);

  CREATE TABLE IF NOT EXISTS slskd_transfer_history (
    id TEXT PRIMARY KEY,
    job_id TEXT,
    username TEXT NOT NULL,
    remote_filename TEXT,
    transfer_id TEXT,
    search_id TEXT,
    batch_id TEXT,
    status TEXT NOT NULL,
    reason TEXT,
    score DOUBLE PRECISION,
    artist_name TEXT,
    track_name TEXT,
    album_name TEXT,
    source_path TEXT,
    final_path TEXT,
    actual_duration_ms BIGINT,
    created_at BIGINT NOT NULL,
    cleaned_at BIGINT
  );
  CREATE INDEX IF NOT EXISTS idx_slskd_transfer_history_username
    ON slskd_transfer_history (username, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_slskd_transfer_history_created_at
    ON slskd_transfer_history (created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_slskd_transfer_history_status
    ON slskd_transfer_history (status, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_slskd_transfer_history_cleanup
    ON slskd_transfer_history (cleaned_at, created_at DESC);

  CREATE TABLE IF NOT EXISTS honker_task_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    queue TEXT NOT NULL,
    name TEXT,
    payload TEXT,
    worker_id TEXT,
    attempt INTEGER,
    status TEXT NOT NULL,
    error TEXT,
    queued_at BIGINT,
    run_at BIGINT,
    started_at BIGINT NOT NULL,
    ended_at BIGINT,
    duration_ms BIGINT,
    created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM now())::BIGINT
  );
  CREATE INDEX IF NOT EXISTS idx_honker_task_runs_started_at ON honker_task_runs (started_at DESC);
  CREATE INDEX IF NOT EXISTS idx_honker_task_runs_queue_started ON honker_task_runs (queue, started_at DESC);
  CREATE INDEX IF NOT EXISTS idx_honker_task_runs_job ON honker_task_runs (job_id, queue);
`;

// Genres live under $.genres, $.genre, $.common.genre or $.tags.genre as a
// string or an array of strings.
const GENRE_FUNCTIONS = `
  CREATE OR REPLACE FUNCTION aurral_genres(metadata TEXT) RETURNS SETOF TEXT
  LANGUAGE sql IMMUTABLE STRICT AS $$
    WITH doc AS (SELECT aurral_json(metadata) AS body),
    candidates AS (
      SELECT body -> 'genres' AS value FROM doc
      UNION ALL SELECT body -> 'genre' FROM doc
      UNION ALL SELECT body -> 'common' -> 'genre' FROM doc
      UNION ALL SELECT body -> 'tags' -> 'genre' FROM doc
    ),
    expanded AS (
      SELECT CASE
        WHEN jsonb_typeof(value) = 'array' THEN element.text_value
        ELSE value #>> '{}'
      END AS genre
      FROM candidates
      LEFT JOIN LATERAL (
        SELECT jsonb_array_elements_text(value) AS text_value
        WHERE jsonb_typeof(value) = 'array'
      ) AS element ON TRUE
      WHERE value IS NOT NULL AND jsonb_typeof(value) <> 'null'
    )
    SELECT DISTINCT trim(genre) FROM expanded WHERE genre IS NOT NULL AND trim(genre) <> '';
  $$;

  CREATE OR REPLACE FUNCTION aurral_sync_entity_genres(kind TEXT, entity BIGINT, metadata TEXT)
  RETURNS VOID LANGUAGE plpgsql AS $$
  BEGIN
    DELETE FROM library_genres WHERE entity_kind = kind AND entity_id = entity;
    INSERT INTO library_genres (entity_kind, entity_id, genre)
    SELECT kind, entity, genre FROM aurral_genres(metadata) AS genre
    ON CONFLICT DO NOTHING;
  END;
  $$;

  CREATE OR REPLACE FUNCTION aurral_library_genres_trigger() RETURNS TRIGGER
  LANGUAGE plpgsql AS $$
  DECLARE
    kind TEXT := TG_ARGV[0];
  BEGIN
    IF TG_OP = 'DELETE' THEN
      DELETE FROM library_genres WHERE entity_kind = kind AND entity_id = OLD.id;
      RETURN OLD;
    END IF;
    IF TG_OP = 'UPDATE' AND NEW.metadata_json IS NOT DISTINCT FROM OLD.metadata_json THEN
      RETURN NEW;
    END IF;
    PERFORM aurral_sync_entity_genres(kind, NEW.id, NEW.metadata_json);
    RETURN NEW;
  END;
  $$;
`;

const RECENCY_FUNCTIONS = `
  CREATE OR REPLACE FUNCTION aurral_refresh_track_recency(track_ids BIGINT[]) RETURNS VOID
  LANGUAGE sql AS $$
    UPDATE library_tracks SET
      latest_media_at = COALESCE((
        SELECT MAX(created_at) FROM library_media_files WHERE track_id = library_tracks.id
      ), 0),
      latest_available_media_at = COALESCE((
        SELECT MAX(created_at) FROM library_media_files
        WHERE track_id = library_tracks.id AND available = 1
      ), 0)
    WHERE id = ANY (track_ids);
  $$;

  CREATE OR REPLACE FUNCTION aurral_refresh_album_recency(album_ids BIGINT[]) RETURNS VOID
  LANGUAGE sql AS $$
    UPDATE library_albums SET
      latest_media_at = COALESCE((
        SELECT MAX(media.created_at)
        FROM library_album_tracks AS album_track
        JOIN library_media_files AS media
          ON media.track_id = album_track.track_id
          AND (media.album_id = album_track.album_id OR media.album_id IS NULL)
        WHERE album_track.album_id = library_albums.id
      ), 0),
      latest_available_media_at = COALESCE((
        SELECT MAX(media.created_at)
        FROM library_album_tracks AS album_track
        JOIN library_media_files AS media
          ON media.track_id = album_track.track_id
          AND (media.album_id = album_track.album_id OR media.album_id IS NULL)
        WHERE album_track.album_id = library_albums.id AND media.available = 1
      ), 0)
    WHERE id = ANY (album_ids);
  $$;

  -- Albums a media row counts for: its own album plus, when album_id is NULL,
  -- every album the track is linked to.
  CREATE OR REPLACE FUNCTION aurral_media_album_ids(media_track_id BIGINT, media_album_id BIGINT)
  RETURNS BIGINT[] LANGUAGE sql STABLE AS $$
    SELECT COALESCE(array_agg(DISTINCT album_id), '{}'::BIGINT[]) FROM (
      SELECT media_album_id AS album_id WHERE media_album_id IS NOT NULL
      UNION
      SELECT album_id FROM library_album_tracks WHERE track_id = media_track_id
    ) AS albums;
  $$;

  CREATE OR REPLACE FUNCTION aurral_media_files_recency_trigger() RETURNS TRIGGER
  LANGUAGE plpgsql AS $$
  BEGIN
    IF TG_OP = 'INSERT' THEN
      -- Inserts only raise the stored maximum (bulk scan path).
      UPDATE library_tracks SET
        latest_media_at = GREATEST(latest_media_at, COALESCE(NEW.created_at, 0)),
        latest_available_media_at = CASE WHEN NEW.available = 1
          THEN GREATEST(latest_available_media_at, COALESCE(NEW.created_at, 0))
          ELSE latest_available_media_at END
      WHERE id = NEW.track_id;
      UPDATE library_albums SET
        latest_media_at = GREATEST(latest_media_at, COALESCE(NEW.created_at, 0)),
        latest_available_media_at = CASE WHEN NEW.available = 1
          THEN GREATEST(latest_available_media_at, COALESCE(NEW.created_at, 0))
          ELSE latest_available_media_at END
      WHERE id = ANY (aurral_media_album_ids(NEW.track_id, NEW.album_id));
      RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
      PERFORM aurral_refresh_track_recency(ARRAY[OLD.track_id, NEW.track_id]);
      PERFORM aurral_refresh_album_recency(
        aurral_media_album_ids(OLD.track_id, OLD.album_id) || aurral_media_album_ids(NEW.track_id, NEW.album_id)
      );
      RETURN NEW;
    ELSE
      PERFORM aurral_refresh_track_recency(ARRAY[OLD.track_id]);
      PERFORM aurral_refresh_album_recency(aurral_media_album_ids(OLD.track_id, OLD.album_id));
      RETURN OLD;
    END IF;
  END;
  $$;

  CREATE OR REPLACE FUNCTION aurral_album_tracks_recency_trigger() RETURNS TRIGGER
  LANGUAGE plpgsql AS $$
  BEGIN
    IF TG_OP = 'INSERT' THEN
      UPDATE library_albums SET
        latest_media_at = GREATEST(latest_media_at, COALESCE((
          SELECT MAX(created_at) FROM library_media_files
          WHERE track_id = NEW.track_id AND (album_id = NEW.album_id OR album_id IS NULL)
        ), 0)),
        latest_available_media_at = GREATEST(latest_available_media_at, COALESCE((
          SELECT MAX(created_at) FROM library_media_files
          WHERE track_id = NEW.track_id AND (album_id = NEW.album_id OR album_id IS NULL)
            AND available = 1
        ), 0))
      WHERE id = NEW.album_id;
      RETURN NEW;
    ELSE
      PERFORM aurral_refresh_album_recency(ARRAY[OLD.album_id]);
      RETURN OLD;
    END IF;
  END;
  $$;
`;

const TRIGGERS = `
  DROP TRIGGER IF EXISTS library_media_files_recency ON library_media_files;
  CREATE TRIGGER library_media_files_recency
    AFTER INSERT OR UPDATE OF track_id, album_id, available, created_at OR DELETE
    ON library_media_files
    FOR EACH ROW EXECUTE FUNCTION aurral_media_files_recency_trigger();

  DROP TRIGGER IF EXISTS library_album_tracks_recency ON library_album_tracks;
  CREATE TRIGGER library_album_tracks_recency
    AFTER INSERT OR DELETE ON library_album_tracks
    FOR EACH ROW EXECUTE FUNCTION aurral_album_tracks_recency_trigger();

  DROP TRIGGER IF EXISTS library_artists_genres ON library_artists;
  CREATE TRIGGER library_artists_genres
    AFTER INSERT OR UPDATE OF metadata_json OR DELETE ON library_artists
    FOR EACH ROW EXECUTE FUNCTION aurral_library_genres_trigger('artist');

  DROP TRIGGER IF EXISTS library_albums_genres ON library_albums;
  CREATE TRIGGER library_albums_genres
    AFTER INSERT OR UPDATE OF metadata_json OR DELETE ON library_albums
    FOR EACH ROW EXECUTE FUNCTION aurral_library_genres_trigger('album');

  DROP TRIGGER IF EXISTS library_tracks_genres ON library_tracks;
  CREATE TRIGGER library_tracks_genres
    AFTER INSERT OR UPDATE OF metadata_json OR DELETE ON library_tracks
    FOR EACH ROW EXECUTE FUNCTION aurral_library_genres_trigger('track');
`;

export const MIGRATIONS = [
  { id: "0001_initial_tables", sql: INITIAL_TABLES },
  { id: "0002_genre_functions", sql: GENRE_FUNCTIONS },
  { id: "0003_recency_functions", sql: RECENCY_FUNCTIONS },
  { id: "0004_triggers", sql: TRIGGERS },
];

export async function migrateDatabase(db, { logger = console } = {}) {
  await db.exec(`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      id TEXT PRIMARY KEY,
      applied_at BIGINT NOT NULL
    )
  `);
  // Serializes concurrent starters (main thread plus workers) on one lock.
  return db.transaction(async () => {
    await db.exec("SELECT pg_advisory_xact_lock(725401)");
    const applied = new Set(
      (await db.all("SELECT id FROM schema_migrations")).map((row) => row.id),
    );
    const ran = [];
    for (const migration of MIGRATIONS) {
      if (applied.has(migration.id)) continue;
      await db.exec(migration.sql);
      await db.run("INSERT INTO schema_migrations (id, applied_at) VALUES (?, ?)", [
        migration.id,
        Date.now(),
      ]);
      ran.push(migration.id);
    }
    if (ran.length) logger.info?.("db", "Applied database migrations", { migrations: ran });
    return ran;
  });
}
